
"""Add thank you screen fields to forms

Revision ID: 9fd65f36b697
Revises: 1c67bf148dd9
Create Date: 2026-07-27 13:16:34.505334

"""
from alembic import op
import sqlalchemy as sa


revision = '9fd65f36b697'
down_revision = '1c67bf148dd9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('forms', sa.Column('thank_you_title', sa.String(), nullable=True))
    op.add_column('forms', sa.Column('thank_you_subtitle', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('forms', 'thank_you_subtitle')
    op.drop_column('forms', 'thank_you_title')
    # ### end Alembic commands ###
